
title: Mary Ruoro
email: mariaruoro@gmail.com
description: >-
  Personal site and blog for Mary Ruoro, CEO and Founder of a Kenyan EdTech company.
baseurl: ""
url: "https://pink404fairy.github.io"
theme: minima
plugins:
  - jekyll-feed
