
title: Mary Ruoro
email: your-email@example.com
description: >-
  Personal site and blog for Mary Ruoro, CEO and Founder of a Kenyan EdTech company.
baseurl: ""
url: "https://maryruoro.github.io"
theme: minima
plugins:
  - jekyll-feed
